In [12]:
import torch
import torch.nn as nn
from pprint import pprint


In [13]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        # self.fc = nn.Linear(10, 2)
        self.fc1 = nn.Linear(10, 2)
        nn.init.xavier_uniform_(self.fc1.weight)
        nn.init.zeros_(self.fc1.bias)

        self.fc2 = nn.Linear(2, 2)
        self.relu = nn.ReLU()

        self.net = nn.Sequential(self.fc1, self.relu, self.fc2)

    def forward(self, x):
        # return self.fc2(self.relu(self.fc1(x)))
        return self.net(x)

model = MyModel()

In [14]:

x = torch.randn(3, 10) # 3个样本, 每个样本10个特征
output = model(x)

pprint(model.named_parameters)

<bound method Module.named_parameters of MyModel(
  (fc1): Linear(in_features=10, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=2, bias=True)
  (relu): ReLU()
  (net): Sequential(
    (0): Linear(in_features=10, out_features=2, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2, out_features=2, bias=True)
  )
)>


In [15]:
pprint(model.state_dict())
torch.save(model, 'my_model.pt')

OrderedDict([('fc1.weight',
              tensor([[-0.4222, -0.0734,  0.5706,  0.6512, -0.5544,  0.5636, -0.0607, -0.1926,
          0.4247, -0.4684],
        [-0.1239,  0.0356,  0.6194,  0.6466, -0.4727, -0.1065, -0.3358,  0.4134,
          0.1044,  0.3194]])),
             ('fc1.bias', tensor([0., 0.])),
             ('fc2.weight',
              tensor([[-0.2419,  0.5291],
        [ 0.7070,  0.4262]])),
             ('fc2.bias', tensor([ 0.5257, -0.1164])),
             ('net.0.weight',
              tensor([[-0.4222, -0.0734,  0.5706,  0.6512, -0.5544,  0.5636, -0.0607, -0.1926,
          0.4247, -0.4684],
        [-0.1239,  0.0356,  0.6194,  0.6466, -0.4727, -0.1065, -0.3358,  0.4134,
          0.1044,  0.3194]])),
             ('net.0.bias', tensor([0., 0.])),
             ('net.2.weight',
              tensor([[-0.2419,  0.5291],
        [ 0.7070,  0.4262]])),
             ('net.2.bias', tensor([ 0.5257, -0.1164]))])


In [16]:
another_model = torch.load('my_model.pt', weights_only=False)
pprint(another_model.state_dict())

OrderedDict([('fc1.weight',
              tensor([[-0.4222, -0.0734,  0.5706,  0.6512, -0.5544,  0.5636, -0.0607, -0.1926,
          0.4247, -0.4684],
        [-0.1239,  0.0356,  0.6194,  0.6466, -0.4727, -0.1065, -0.3358,  0.4134,
          0.1044,  0.3194]])),
             ('fc1.bias', tensor([0., 0.])),
             ('fc2.weight',
              tensor([[-0.2419,  0.5291],
        [ 0.7070,  0.4262]])),
             ('fc2.bias', tensor([ 0.5257, -0.1164])),
             ('net.0.weight',
              tensor([[-0.4222, -0.0734,  0.5706,  0.6512, -0.5544,  0.5636, -0.0607, -0.1926,
          0.4247, -0.4684],
        [-0.1239,  0.0356,  0.6194,  0.6466, -0.4727, -0.1065, -0.3358,  0.4134,
          0.1044,  0.3194]])),
             ('net.0.bias', tensor([0., 0.])),
             ('net.2.weight',
              tensor([[-0.2419,  0.5291],
        [ 0.7070,  0.4262]])),
             ('net.2.bias', tensor([ 0.5257, -0.1164]))])
