In [1]:
import torch
import torch.nn as nn
from pprint import pprint


In [2]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        # self.fc = nn.Linear(10, 2)
        self.fc1 = nn.Linear(10, 2)
        nn.init.xavier_uniform_(self.fc1.weight)
        nn.init.zeros_(self.fc1.bias)

        self.fc2 = nn.Linear(2, 2)
        self.relu = nn.ReLU()

    def forward(self, x):
        return self.fc2(self.relu(self.fc1(x)))

model = MyModel()

In [6]:

x = torch.randn(3, 10) # 3个样本, 每个样本10个特征
output = model(x)

pprint(model.named_parameters)

<bound method Module.named_parameters of MyModel(
  (fc1): Linear(in_features=10, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=2, bias=True)
  (relu): ReLU()
)>


In [4]:
pprint(model.state_dict())
torch.save(model, 'my_model.pt')

OrderedDict([('fc1.weight',
              tensor([[-0.0430,  0.5943,  0.6379,  0.3026, -0.2127,  0.5022, -0.0227, -0.6774,
         -0.4930,  0.4653],
        [-0.5238, -0.1877, -0.1019, -0.6389,  0.6757,  0.4833, -0.2907,  0.0039,
         -0.6728,  0.6907]])),
             ('fc1.bias', tensor([0., 0.])),
             ('fc2.weight',
              tensor([[ 0.2009, -0.6346],
        [-0.3098,  0.1237]])),
             ('fc2.bias', tensor([-0.6689, -0.3971]))])


In [5]:
another_model = torch.load('my_model.pt', weights_only=False)
pprint(another_model.state_dict())

OrderedDict([('fc1.weight',
              tensor([[-0.0430,  0.5943,  0.6379,  0.3026, -0.2127,  0.5022, -0.0227, -0.6774,
         -0.4930,  0.4653],
        [-0.5238, -0.1877, -0.1019, -0.6389,  0.6757,  0.4833, -0.2907,  0.0039,
         -0.6728,  0.6907]])),
             ('fc1.bias', tensor([0., 0.])),
             ('fc2.weight',
              tensor([[ 0.2009, -0.6346],
        [-0.3098,  0.1237]])),
             ('fc2.bias', tensor([-0.6689, -0.3971]))])
