In [6]:
import torch
import torch.nn as nn
from pprint import pprint

In [7]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        # self.fc = nn.Linear(10, 2)
        self.fc1 = nn.Linear(10, 2)
        nn.init.xavier_uniform_(self.fc1.weight)
        nn.init.zeros_(self.fc1.bias)

        self.fc2 = nn.Linear(2, 2)
        self.relu = nn.ReLU()

    def forward(self, x):
        return self.fc2(self.relu(self.fc1(x)))

model = MyModel()

In [8]:

x = torch.randn(3, 10) # 3个样本, 每个样本10个特征
output = model(x)

pprint(model.named_parameters)

<bound method Module.named_parameters of MyModel(
  (fc1): Linear(in_features=10, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=2, bias=True)
  (relu): ReLU()
)>


In [9]:
pprint(model.state_dict())
torch.save(model, 'my_model.pt')

OrderedDict([('fc1.weight',
              tensor([[-0.2343, -0.2906, -0.2853, -0.2570, -0.1987,  0.2964,  0.0774, -0.0720,
         -0.2778,  0.2912],
        [ 0.0357, -0.1004,  0.0704,  0.1654,  0.1658,  0.1710,  0.2429,  0.0734,
         -0.1867,  0.2500]])),
             ('fc1.bias', tensor([ 0.1390, -0.1379])),
             ('fc2.weight',
              tensor([[ 0.3925, -0.5116],
        [ 0.6813,  0.2151]])),
             ('fc2.bias', tensor([-0.6237,  0.3767]))])


In [10]:
another_model = torch.load('my_model.pt', weights_only=False)
pprint(another_model.state_dict())

OrderedDict([('fc1.weight',
              tensor([[-0.2343, -0.2906, -0.2853, -0.2570, -0.1987,  0.2964,  0.0774, -0.0720,
         -0.2778,  0.2912],
        [ 0.0357, -0.1004,  0.0704,  0.1654,  0.1658,  0.1710,  0.2429,  0.0734,
         -0.1867,  0.2500]])),
             ('fc1.bias', tensor([ 0.1390, -0.1379])),
             ('fc2.weight',
              tensor([[ 0.3925, -0.5116],
        [ 0.6813,  0.2151]])),
             ('fc2.bias', tensor([-0.6237,  0.3767]))])
