In [7]:
import torch
import torch.nn as nn
from pprint import pprint


In [8]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        # self.fc = nn.Linear(10, 2)
        self.fc1 = nn.Linear(10, 2)
        nn.init.xavier_uniform_(self.fc1.weight)
        nn.init.zeros_(self.fc1.bias)

        self.fc2 = nn.Linear(2, 2)
        self.relu = nn.ReLU()

        self.net = nn.Sequential(self.fc1, self.relu, self.fc2)

    def forward(self, x):
        # return self.fc2(self.relu(self.fc1(x)))
        return self.net(x)

model = MyModel()

In [9]:

x = torch.randn(3, 10) # 3个样本, 每个样本10个特征
output = model(x)

pprint(model.named_parameters)

<bound method Module.named_parameters of MyModel(
  (fc1): Linear(in_features=10, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=2, bias=True)
  (relu): ReLU()
  (net): Sequential(
    (0): Linear(in_features=10, out_features=2, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2, out_features=2, bias=True)
  )
)>


In [10]:
pprint(model.state_dict())
torch.save(model, 'my_model.pt')

OrderedDict([('fc1.weight',
              tensor([[ 0.0172, -0.2727,  0.1505,  0.3008, -0.5241,  0.4081, -0.6305, -0.4566,
         -0.1030,  0.4078],
        [ 0.6446,  0.4965,  0.6363,  0.2433, -0.6304, -0.5089, -0.4612,  0.0167,
          0.1006,  0.1534]])),
             ('fc1.bias', tensor([0., 0.])),
             ('fc2.weight',
              tensor([[ 0.6148,  0.3583],
        [ 0.5608, -0.1305]])),
             ('fc2.bias', tensor([0.0009, 0.2116])),
             ('net.0.weight',
              tensor([[ 0.0172, -0.2727,  0.1505,  0.3008, -0.5241,  0.4081, -0.6305, -0.4566,
         -0.1030,  0.4078],
        [ 0.6446,  0.4965,  0.6363,  0.2433, -0.6304, -0.5089, -0.4612,  0.0167,
          0.1006,  0.1534]])),
             ('net.0.bias', tensor([0., 0.])),
             ('net.2.weight',
              tensor([[ 0.6148,  0.3583],
        [ 0.5608, -0.1305]])),
             ('net.2.bias', tensor([0.0009, 0.2116]))])


In [11]:
another_model = torch.load('my_model.pt', weights_only=False)
pprint(another_model.state_dict())

OrderedDict([('fc1.weight',
              tensor([[ 0.0172, -0.2727,  0.1505,  0.3008, -0.5241,  0.4081, -0.6305, -0.4566,
         -0.1030,  0.4078],
        [ 0.6446,  0.4965,  0.6363,  0.2433, -0.6304, -0.5089, -0.4612,  0.0167,
          0.1006,  0.1534]])),
             ('fc1.bias', tensor([0., 0.])),
             ('fc2.weight',
              tensor([[ 0.6148,  0.3583],
        [ 0.5608, -0.1305]])),
             ('fc2.bias', tensor([0.0009, 0.2116])),
             ('net.0.weight',
              tensor([[ 0.0172, -0.2727,  0.1505,  0.3008, -0.5241,  0.4081, -0.6305, -0.4566,
         -0.1030,  0.4078],
        [ 0.6446,  0.4965,  0.6363,  0.2433, -0.6304, -0.5089, -0.4612,  0.0167,
          0.1006,  0.1534]])),
             ('net.0.bias', tensor([0., 0.])),
             ('net.2.weight',
              tensor([[ 0.6148,  0.3583],
        [ 0.5608, -0.1305]])),
             ('net.2.bias', tensor([0.0009, 0.2116]))])
