In [42]:
import torch
import torch.nn as nn
 

In [43]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        # self.fc = nn.Linear(10, 2)
        self.fc1 = nn.Linear(10, 2)
        self.fc2 = nn.Linear(2, 2)
        # self.relu = nn.ReLU()

    def forward(self, x):
        # return self.fc(x)
        return self.fc2(self.fc1(x))
        # return self.relu(self.fc(x))

model = MyModel()

In [44]:
x = torch.randn(3, 10) # 3个样本, 每个样本10个特征
output = model(x)

print([p for p in model.parameters()])
pprint(model.named_parameters)
pprint(f"x: {x}, {x.shape}; Ouput: {output}, {output.shape}")

[Parameter containing:
tensor([[-0.1074, -0.0641,  0.2792,  0.0647, -0.0187,  0.0471,  0.1114,  0.1267,
         -0.0833,  0.2498],
        [ 0.2568,  0.0124, -0.1902,  0.0445,  0.2199,  0.2277,  0.0279,  0.2666,
          0.1771,  0.0235]], requires_grad=True), Parameter containing:
tensor([0.2709, 0.1557], requires_grad=True)]
<bound method Module.named_parameters of MyModel(
  (fc): Linear(in_features=10, out_features=2, bias=True)
)>
('x: tensor([[-7.1130e-01, -6.5041e-01,  2.7662e-02,  1.2507e+00,  '
 '1.2629e+00,\n'
 '         -3.1161e-01,  1.4932e+00, -6.7001e-01,  3.7528e-01,  1.4865e-01],\n'
 '        [ 1.1315e+00,  7.5842e-01,  5.7324e-04, -5.3048e-01,  5.6895e-01,\n'
 '          7.5329e-01, -1.5416e-01, -4.1752e-01,  7.0723e-01, -7.6679e-01],\n'
 '        [-2.5659e-01, -5.1865e-01,  3.8017e-01,  2.3618e-01, -8.0920e-01,\n'
 '          1.7095e-01,  8.9041e-01, -8.7058e-01, -1.3475e-01,  4.1370e-02]]), '
 'torch.Size([3, 10]); Ouput: tensor([[ 0.5265,  0.1552],\n'
 '        [-

In [45]:
pprint(model.state_dict())
torch.save(model, 'my_model.pt')

OrderedDict([('fc.weight',
              tensor([[-0.1074, -0.0641,  0.2792,  0.0647, -0.0187,  0.0471,  0.1114,  0.1267,
         -0.0833,  0.2498],
        [ 0.2568,  0.0124, -0.1902,  0.0445,  0.2199,  0.2277,  0.0279,  0.2666,
          0.1771,  0.0235]])),
             ('fc.bias', tensor([0.2709, 0.1557]))])


In [46]:
another_model = torch.load('my_model.pt', weights_only=False)
pprint(another_model.state_dict())

OrderedDict([('fc.weight',
              tensor([[-0.1074, -0.0641,  0.2792,  0.0647, -0.0187,  0.0471,  0.1114,  0.1267,
         -0.0833,  0.2498],
        [ 0.2568,  0.0124, -0.1902,  0.0445,  0.2199,  0.2277,  0.0279,  0.2666,
          0.1771,  0.0235]])),
             ('fc.bias', tensor([0.2709, 0.1557]))])
